services:
    - type: web
      name: salespro-manager
      env: python
      pythonVersion: 3.11.9
      buildCommand: pip install -r requirements.txt
      startCommand: gunicorn app:app
      envVars:
          - key: DATABASE_URL
            value: postgresql://neondb_owner:MAT_KHAU_THAT@ep-proud-thunder-a4q1y1fz-pooler.us-east-1.aws.neon.tech/neondb?sslmode=require
          - key: SECRET_KEY
            generateValue: true
          - key: FLASK_ENV
            value: production

databases:
    - name: salespro-db
      databaseName: salespro
      user: salespro_user
      plan: free
