services:
  - type: web
    name: salespro-manager
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k eventlet -w 1 app:app
    
    envVars:
      - key: DATABASE_URL
        value: postgresql://neondb_owner:MAT_KHAU_THAT@ep-proud-thunder-a4q1y1fz-pooler.us-east-1.aws.neon.tech/neondb?sslmode=require
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
